namespace: alibaba
name: apsarastack
version: 0.0.1
readme: README.md
authors:
- Wangyu (@zshongyi)
description: Alibaba Cloud
license_file: LICENSE
tags: [alibaba, apsarastack, aliyun, cloud]
#dependencies:
#  ansible.netcommon: '>=0.0.1'
repository: https://github.com/alibaba/ansible.apsarastack.git
homepage: https://github.com/alibaba/ansible.apsarastack
issues: https://github.com/alibaba/ansible.apsarastack/issues